database:
  hostname: "localhost"
  username: "jan"
  password: "123456"
  database_name: "books_db"
  table_name: "books"
  port: "5432"

scraper:
  name: "books"
  url: "https://books.toscrape.com/"
  max_items: 500

http:
  ip: "127.0.0.1"
  port: 8080
