database:
  hostname: "localhost"
  username: "postgres"
  password: "123456"
  database_name: "postgres" # "real_estates_db"
  table_name: "real_estates"
  port: "5432"

scraper:
  name: "reality"
  url: "https://www.sreality.cz/en/search/for-sale/apartments"
  max_items: 500

http:
  ip: "127.0.0.1"
  port: 8080
